name: calculator_app
description: Aplikasi kalkulator sederhana.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  expressions: ^0.2.5+1
  animated_splash_screen: ^1.3.0 # Tambahkan ini untuk animasi splash screen

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile_photo.jpg.jpg
    - assets/logo.gif
  fonts:
    - family: biko
      fonts:
        - asset: assets/fonts/biko.otf
    - family: super
      fonts:
        - asset: assets/fonts/sunday.ttf
    - family: nica
      fonts:
        - asset: assets/fonts/organica.ttf
